"""
Answer Booklet Compiler - Compiles Q&A into formatted Word/PDF documents
"""

import asyncio
from typing import List, Dict, Any
from pathlib import Path
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
from utils.logger import logger


from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, HRFlowable
from reportlab.lib.units import inch


class BookletCompiler:
    """Compile answers into professional Word/PDF documents"""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_styles()

    def _setup_styles(self):
        """Setup custom styles for ReportLab"""
        self.styles.add(
            ParagraphStyle(
                name="SectionHeader",
                parent=self.styles["Heading1"],
                fontSize=18,
                alignment=1,  # Center
                spaceAfter=12,
            )
        )
        self.styles.add(
            ParagraphStyle(
                name="QuestionStyle",
                parent=self.styles["Normal"],
                fontSize=12,
                bold=True,
                leading=14,
                spaceBefore=12,
                spaceAfter=6,
            )
        )
        self.styles.add(
            ParagraphStyle(
                name="AnswerLabel",
                parent=self.styles["Normal"],
                fontSize=11,
                textColor=colors.green,
                bold=True,
                leading=13,
                leftIndent=10,
            )
        )
        self.styles.add(
            ParagraphStyle(
                name="AnswerStyle",
                parent=self.styles["Normal"],
                fontSize=11,
                leading=14,
                leftIndent=20,
                spaceAfter=12,
            )
        )
        self.styles.add(
            ParagraphStyle(
                name="FooterStyle",
                parent=self.styles["Normal"],
                fontSize=9,
                italic=True,
                alignment=1,  # Center
                textColor=colors.grey,
            )
        )

    async def compile_to_word(
        self, answers: List[Dict[str, Any]], output_path: str, original_filename: str
    ) -> str:
        """Compile answers into Word document"""

        try:
            doc = Document()

            # Header section
            self._add_header(doc, original_filename)

            # Add each Q&A pair
            successful_answers = [a for a in answers if a.get("success", False)]

            for idx, answer_data in enumerate(successful_answers, 1):
                self._add_question_answer(doc, answer_data, idx)

                # Add page break after every 3 questions for better printing
                if idx % 3 == 0 and idx < len(successful_answers):
                    doc.add_page_break()

            # Footer with generation info
            self._add_footer(doc, len(successful_answers))

            # Save document
            output_file = Path(output_path)
            output_file.parent.mkdir(parents=True, exist_ok=True)

            await asyncio.to_thread(doc.save, str(output_file))

            logger.info(f"Compiled answer booklet: {output_file}")
            return str(output_file)

        except Exception as e:
            logger.error(f"Error compiling Word document: {str(e)}")
            raise

    async def compile_to_pdf(
        self, answers: List[Dict[str, Any]], output_path: str, original_filename: str
    ) -> str:
        """Compile answers into PDF document using ReportLab (No Word required)"""

        try:
            output_file = Path(output_path)
            output_file.parent.mkdir(parents=True, exist_ok=True)

            # Generate Word version too for user convenience
            word_path = str(output_file).replace(".pdf", ".docx")
            await self.compile_to_word(answers, word_path, original_filename)

            # Create PDF
            doc = SimpleDocTemplate(
                str(output_file),
                pagesize=A4,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=72,
            )

            story = []

            # Header
            story.append(Paragraph("ANSWER BOOKLET", self.styles["SectionHeader"]))
            story.append(
                Paragraph(f"<b>FOR: {original_filename}</b>", self.styles["Normal"])
            )
            story.append(
                Paragraph(
                    "<i>Generated by EduSolve</i>",
                    ParagraphStyle(
                        "sub", parent=self.styles["Normal"], alignment=1, textColor=colors.grey
                    ),
                )
            )
            story.append(Spacer(1, 0.2 * inch))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.black))
            story.append(Spacer(1, 0.2 * inch))

            # Questions
            successful_answers = [a for a in answers if a.get("success", False)]

            for idx, answer_data in enumerate(successful_answers, 1):
                q_num = answer_data.get("question_number", idx)
                q_text = answer_data.get("question_text", "N/A")
                marks = answer_data.get("marks", 0)
                ans_text = answer_data.get("answer", "N/A")

                # Question Paragraph
                q_para = f"<b>Q{q_num}. {q_text}</b> <font color='darkblue'><i>[{marks} marks]</i></font>"
                story.append(Paragraph(q_para, self.styles["QuestionStyle"]))

                # Answer
                story.append(Paragraph("Answer:", self.styles["AnswerLabel"]))
                story.append(Paragraph(ans_text, self.styles["AnswerStyle"]))

                # Separator
                story.append(HRFlowable(width="80%", thickness=0.5, color=colors.grey))
                story.append(Spacer(1, 0.1 * inch))

                # Page break logic (approximate)
                if idx % 4 == 0 and idx < len(successful_answers):
                    story.append(PageBreak())

            # Footer
            story.append(Spacer(1, 0.5 * inch))
            footer_text = (
                f"Total Questions Answered: {len(successful_answers)}<br/>"
                f'Generated on: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}<br/>'
                f"Powered by EduSolve"
            )
            story.append(Paragraph(footer_text, self.styles["FooterStyle"]))

            # Save PDF
            await asyncio.to_thread(doc.build, story)

            logger.info(f"Direct PDF compiled successfully: {output_file}")
            return str(output_file)

        except Exception as e:
            logger.error(f"Error compiling direct PDF: {str(e)}")
            # Fallback to Word if word_path exists
            if "word_path" in locals() and Path(word_path).exists():
                logger.warning("PDF generation failed, returning Word document")
                return word_path
            raise


    def _add_header(self, doc: Document, original_filename: str):
        """Add header to document"""

        # Title
        title = doc.add_heading("ANSWER BOOKLET", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Subtitle
        subtitle = doc.add_paragraph(f"FOR: {original_filename}")
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle.runs[0].font.size = Pt(14)
        subtitle.runs[0].bold = True

        # Generated by line
        generated = doc.add_paragraph("Generated by EduSolve")
        generated.alignment = WD_ALIGN_PARAGRAPH.CENTER
        generated.runs[0].font.size = Pt(10)
        generated.runs[0].italic = True
        generated.runs[0].font.color.rgb = RGBColor(128, 128, 128)

        # Separator
        doc.add_paragraph("=" * 80)
        doc.add_paragraph()

    def _add_question_answer(
        self, doc: Document, answer_data: Dict[str, Any], index: int
    ):
        """Add single Q&A pair to document with optimized spacing"""

        question_number = answer_data.get("question_number", index)
        question_text = answer_data.get("question_text", "N/A")
        marks = answer_data.get("marks", 0)
        answer_text = answer_data.get("answer", "N/A")

        # Question header (more compact)
        q_header = doc.add_paragraph()
        q_header.paragraph_format.space_before = Pt(6)  # Reduced spacing
        q_header.paragraph_format.space_after = Pt(3)
        q_header_run = q_header.add_run(f"Q{question_number}. {question_text} ")
        q_header_run.font.size = Pt(12)
        q_header_run.bold = True

        # Marks indicator
        marks_run = q_header.add_run(f"[{marks} marks]")
        marks_run.font.size = Pt(11)
        marks_run.font.color.rgb = RGBColor(0, 102, 204)
        marks_run.italic = True

        # Answer label (no extra paragraph)
        answer_label = doc.add_paragraph()
        answer_label.paragraph_format.space_before = Pt(3)
        answer_label.paragraph_format.space_after = Pt(3)
        answer_label_run = answer_label.add_run("Answer:")
        answer_label_run.bold = True
        answer_label_run.font.size = Pt(11)
        answer_label_run.font.color.rgb = RGBColor(0, 128, 0)

        # Answer text (optimized spacing)
        answer_para = doc.add_paragraph(answer_text)
        answer_para.style = "Normal"
        answer_para.paragraph_format.left_indent = Inches(0.25)
        answer_para.paragraph_format.line_spacing = 1.15
        answer_para.paragraph_format.space_after = Pt(6)  # Reduced

        # Separator (lighter)
        separator = doc.add_paragraph("─" * 60)  # Shorter line
        separator.paragraph_format.space_before = Pt(6)
        separator.paragraph_format.space_after = Pt(6)

    def _add_footer(self, doc: Document, total_answers: int):
        """Add footer information"""

        doc.add_paragraph()
        footer = doc.add_paragraph(
            f"\nTotal Questions Answered: {total_answers}\n"
            f'Generated on: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}\n'
            f"Powered by EduSolve - GenAI Answer Generation System"
        )
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].italic = True
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
